[env]
platform = espressif32@6.11.0
platform_packages = platformio/tool-cmake@3.30.2
board = esp32dev
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
build_flags = -Wall -Wextra -Werror
extra_scripts = post:tools/merge_firmware.py

[env:detector]

[env:wiring]
build_flags = ${env.build_flags} -DWIRING_TEST=1

[env:record]
monitor_speed = 921600
build_flags = ${env.build_flags} -DRECORD_AUDIO=1

[env:stress]
build_flags = ${env.build_flags} -DFEATURE_DELAY_MS=80

[env:detector_fp16]
build_flags = ${env.build_flags} -DMODEL_PRECISION=16

[env:detector_int16]
build_flags = ${env.build_flags} -DMODEL_PRECISION=-16

[env:detector_int8]
build_flags = ${env.build_flags} -DMODEL_PRECISION=8

[env:detector_int4]
build_flags = ${env.build_flags} -DMODEL_PRECISION=4
